### ISSUE TITLE
ExtractFields does not recognize GERP++ fields in VCF header

### ISSUE THREAD

**Issue by mlist** [pcingola/SnpSift#27]
The extract fields command does not recognize the ++ when I try to extract GERP++ scores from a VCF file. 

```
Exception in thread "main" java.lang.RuntimeException: INFO field 'dbNSFP_GERP' not found in VCF header
	at ca.mcgill.mcb.pcingola.snpSift.lang.expression.Field.getReturnType(Field.java:232)
	at ca.mcgill.mcb.pcingola.snpSift.lang.expression.Field.eval(Field.java:56)
	at ca.mcgill.mcb.pcingola.snpSift.SnpSiftCmdExtractFields.evaluate(SnpSiftCmdExtractFields.java:43)
	at ca.mcgill.mcb.pcingola.snpSift.SnpSiftCmdExtractFields.run(SnpSiftCmdExtractFields.java:145)
	at ca.mcgill.mcb.pcingola.snpSift.SnpSiftCmdExtractFields.run(SnpSiftCmdExtractFields.java:117)
	at ca.mcgill.mcb.pcingola.snpSift.SnpSift.run(SnpSift.java:334)
	at ca.mcgill.mcb.pcingola.snpSift.SnpSift.main(SnpSift.java:69)
```

**Comment by pcingola** [comment]
There is a specific comment on how to deal with GERP++ in the 
documentation:

"... can get confused if the VCF field has non-alphanumeric charaters in the name (e.g. dbNSFP_GERP++_RS has two "+" signs). A quick fix, it so is to change the field names in the VCF file. Here is an example: "

    # Change field names in VCF
    $ cat kath.vcf | sed "s/dbNSFP_GERP++/dbNSFP_GERP/g" > kath.gerp.vcf

I hope this helps.

**Comment by mlist** [comment]
Sorry I missed that in the documentation. The work-around helped. Thanks!
