### ISSUE TITLE
SnpSift vcfCheck broken in v4.3o

### ISSUE THREAD

**Issue by nsoranzo** [pcingola/SnpSift#41]
```
$ SnpSift vcfCheck foo.vcf
Exception in thread "main" java.lang.NullPointerException
	at org.snpsift.SnpSiftCmdVcfCheck.run(SnpSiftCmdVcfCheck.java:56)
	at org.snpsift.SnpSift.run(SnpSift.java:586)
	at org.snpsift.SnpSift.main(SnpSift.java:76)
```

**Comment by pcingola** [comment]
Fixed. Will release a new version today.
Thank you for the heads up!
